name: Telegram Automation

"on":
  schedule:
    - cron: "30 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install telethon

      - name: Run Telegram Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          MESSAGE: ${{ secrets.MESSAGE }}
        run: python telegram_auto.py
